# Generated by Django 3.2.5 on 2021-07-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('DXpath', models.CharField(max_length=400)),
                ('BXpath', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
