# Generated by Django 3.2.5 on 2021-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='BXpath',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='new',
            name='DXpath',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='new',
            name='row',
            field=models.IntegerField(max_length=100),
        ),
    ]
