# Generated by Django 3.2.5 on 2021-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20210802_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='row',
            field=models.IntegerField(),
        ),
    ]
