# Generated by Django 3.2.5 on 2021-08-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_new_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='row',
            new_name='col',
        ),
    ]
