# Generated by Django 3.2.5 on 2021-09-20 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20210910_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='scraper',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
