# Generated by Django 3.2.5 on 2021-09-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20210921_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='scraper',
        ),
    ]
