# Generated by Django 3.2.5 on 2021-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20210922_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestwithBuzz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('BXpath', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=200)),
                ('DXpath', models.CharField(max_length=300)),
                ('col', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
