# Generated by Django 3.2.5 on 2021-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pages',
            field=models.CharField(max_length=100),
        ),
    ]
