# Generated by Django 3.2.5 on 2021-09-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_file_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_upload',
            new_name='file',
        ),
    ]
