# Generated by Django 3.2.5 on 2021-10-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_rename_file_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='file',
        ),
    ]
