# Generated by Django 3.2.5 on 2021-11-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MIN', models.IntegerField(max_length=2)),
                ('HR', models.IntegerField(max_length=2)),
                ('DAYMONTH', models.IntegerField(max_length=2)),
                ('MONTH', models.IntegerField(max_length=2)),
                ('DAYWEEK', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='col',
        ),
    ]
