# Generated by Django 3.2.5 on 2021-11-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_sche_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sche',
            name='DAYMONTH',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sche',
            name='DAYWEEK',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sche',
            name='HR',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sche',
            name='MIN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sche',
            name='MONTH',
            field=models.IntegerField(),
        ),
    ]
